name: purple_store
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  intl: ^0.17.0
  http: ^0.13.4
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icons_launcher: ^1.1.8

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/launcher_icon/ic_launcher.png"
  adaptive_icon_background: "assets/images/launcher_icon/ic_background.png"
  adaptive_icon_foreground: "assets/images/launcher_icon/ic_foreground.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/product-placeholder.png

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
